//To know which exception has been generated by the try block
public class exception_handler_with_multiple_method
{
	public static void main(String[] args)
	{
		int a=2;
		int c=0;
		int b[]={1,2,3,4};
		System.out.println("Start Program");
		try{
			c=a/0;
			for(int i=0;i<=b.length;i++)
			{
				System.out.println(b[i]);
			}
		} catch(Exception e)
		{
			String s=e.toString();

			System.out.println(s);							//to stored the object into var(because 'e' had stored the string type )
			System.out.println();
			System.out.println("Exception Generated "+e);         //System.out.println(e);
			System.out.println();
			System.out.println(e.getMessage());					//System.out.println(e.getMessage);
			System.out.println();
			e.printStackTrace();								//e.printStackTrace();
			System.out.println();
		}
		System.out.println("End Program");
	}
}